# Generated by bin/sync-formulae.mjs from the gmackie/forgec v0.4.0 release. Do not edit by hand.
class Forgec < Formula
  desc "ForgeGraph compiler: one package, equivalent behaviour on Cloudflare, AWS and Node"
  homepage "https://github.com/gmackie/forgec"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gmackie/forgec/releases/download/v0.4.0/forgec-0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "8d0414aa4ff32f3e98ed96b18a6212836269b7d0775c8853303ffe5c3aa1c59a"
    elsif Hardware::CPU.intel?
      url "https://github.com/gmackie/forgec/releases/download/v0.4.0/forgec-0.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "818b384592815f4a8420c87418bd82ae2c085673a2b844c0e7218bc917bccc0a"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/gmackie/forgec/releases/download/v0.4.0/forgec-0.4.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cd7cf42723ffbb7ca0859951eb313ca25e775ea68466b873533ac6b79aada5e3"
    elsif Hardware::CPU.intel?
      url "https://github.com/gmackie/forgec/releases/download/v0.4.0/forgec-0.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "bb7c588bb37e2fd3230bed427a4619b5f0d1282dc0e54f07f0503f1f96fca434"
    end
  end

  def install
    bin.install "forgec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/forgec --version")
  end
end
