# Generated by bin/sync-formulae.mjs from the gmackie/forgec v0.3.0 release. Do not edit by hand.
class Forgec < Formula
  desc "ForgeGraph compiler: one package, equivalent behaviour on Cloudflare, AWS and Node"
  homepage "https://github.com/gmackie/forgec"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gmackie/forgec/releases/download/v0.3.0/forgec-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "799e4e26730068418572acd388a5e6c8e6fe5b8f0094ab677e46146520f02c3e"
    elsif Hardware::CPU.intel?
      url "https://github.com/gmackie/forgec/releases/download/v0.3.0/forgec-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "580a8a3d9c19d737f8407935064aaf16ca543c62d74d9225c641fc285d2d097d"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/gmackie/forgec/releases/download/v0.3.0/forgec-0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c2f52dc4025023110c19530302696d0c9073d5cce65978aae8949a16ca3502c4"
    elsif Hardware::CPU.intel?
      url "https://github.com/gmackie/forgec/releases/download/v0.3.0/forgec-0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b9c567f9259577ed545f55053deb63a72060db17ea1c58e75e6860e7fe21c3f3"
    end
  end

  def install
    bin.install "forgec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/forgec --version")
  end
end
